version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: ${DB_CONTAINER_NAME}
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASSWD}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./db/mycnf:/etc/mysql/conf.d/my.cnf
      - db-volume:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  db-volume:
