version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    volumes:
      - .:/go/src
    tty: true
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql
    networks:
      - blog-app-net

  mysql:
    image: mysql:5.7
    container_name: ${DB_CONTAINER_NAME}
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASSWD}
      TZ: "Asia/Tokyo"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./db/mycnf:/etc/mysql/conf.d/my.cnf
      - db-volume:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  db-volume:

networks:
  blog-app-net:
    driver: bridge